# Generated by Django 3.2.5 on 2021-08-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_render', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='pet',
            new_name='profile',
        ),
    ]
