# Generated by Django 3.2.5 on 2021-08-04 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_auth', '0001_initial'),
        ('profiles_render', '0002_rename_pet_like_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='profile',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='profile_auth.profile'),
            preserve_default=False,
        ),
    ]
