# Generated by Django 3.2.5 on 2021-08-04 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_auth', '0001_initial'),
        ('profiles_render', '0003_alter_like_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_auth.profile'),
        ),
    ]
